### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon.

### ISSUE THREAD

**Issue by brechtm** [jannekem/run-python-script-action#8]
GitHub started printing this warning on _set-output_ commands:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

You should change the `set_output` and `save_state` functions in util.py to print to the files pointed to by the `GITHUB_OUTPUT` and `GITHUB_STATE` environment variables instead of stdout.

**Comment by jannekem** [comment]
Thanks for reporting the issue! I changed `set_output` and `save_state` to work with the same logic as the similar path and env functions so this should fix the warning. Could you verify that the fix in PR #9 works for your use case?

**Comment by brechtm** [comment]
I ran a test here, but I'm still getting the warnings: https://github.com/brechtm/rinohtype/actions/runs/3328038096/jobs/5503560278#step:8:31 (Determine directory to publish docs to)

Maybe I just can't select this PR's branch using the @ notation as I did in https://github.com/brechtm/rinohtype/commit/8973a99180bd2c8de05ce55829827e30fcf879fe? You might need to create a tag.

**Comment by brechtm** [comment]
I also tried specifying the commit SHA instead of the branch name: same result. https://github.com/brechtm/rinohtype/actions/runs/3328256124/jobs/5504042677#step:8:31

I'm sure there's a simple explanation for this, but at this moment I have no clue.

Relevant GitHub documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses

**Comment by brechtm** [comment]
I think this is due to code in `dist/index.js`.

**Comment by jannekem** [comment]
Ah, I missed that I'm also setting the `stdout`, `stderr` and `error` outputs in [index.js](https://github.com/jannekem/run-python-script-action/blob/main/index.js#L37). This should now be fixed on the PR as I've upgraded the `@actions/core` dependency to version `1.10.0` as mentioned in the blog post.

**Comment by brechtm** [comment]
Looks good now!
https://github.com/brechtm/rinohtype/actions/runs/3338924705/jobs/5527216914#step:8:29

**Comment by jannekem** [comment]
The was published as [v1.4](https://github.com/jannekem/run-python-script-action/releases/tag/v1.4) and the `v1` tag has been updated to point to this release.
